import { Award, BookOpen, Building2, CalendarDays, IndianRupee, MapPin, ShieldAlert, UserRound } from 'lucide-react';

export function ScreeningCaseOverview({ application }: { application: Record<string, unknown> }) {
  const held = Boolean(application.IsHeldByAdmin);
  return <section className="glass-card overflow-hidden"><div className="border-b border-border-soft bg-gradient-to-r from-brand/[0.08] via-transparent to-gold/[0.05] p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded border border-brand/10 bg-brand/5 px-2 py-1 font-mono text-[10px] text-brand">APP-{show(application.ApplicationID)}</span><span className="rounded-full border border-brand/10 px-2 py-1 text-[9px] font-semibold uppercase text-text-muted">{show(application.Status)}</span>{held ? <span className="inline-flex items-center gap-1 rounded-full bg-danger/10 px-2 py-1 text-[9px] font-semibold text-danger"><ShieldAlert size={10} />On hold</span> : null}</div>
        <p className="mt-4 text-[10px] uppercase tracking-[0.25em] text-gold">{show(application.ScholarshipName)}</p><h1 className="mt-1 text-3xl font-semibold text-text sm:text-4xl">{show(application.FullName)}</h1><p className="mt-2 text-xs text-text-muted">{show(application.SponsorName)} · {show(application.InstitutionName)}</p></div>
        <div className="rounded-xl border border-brand/10 bg-white/60 p-4 text-right"><p className="text-[9px] uppercase tracking-wider text-text-dim">Recommended award</p><p className="mt-1 font-display text-2xl font-semibold text-text">₹{Number(application.ScholarshipAmount ?? application.PerStudentAmount ?? 0).toLocaleString('en-IN')}</p><p className="mt-1 text-[9px] text-text-dim">Submitted {formatDate(application.SubmissionDate)}</p></div></div></div>
    {held ? <div className="flex gap-2 border-b border-danger/20 bg-danger/10 px-5 py-3 text-xs text-danger"><ShieldAlert className="h-4 w-4 shrink-0" /><div><b>Administrative hold</b><p className="mt-0.5">{show(application.AdminHoldReason, 'Contact an administrator before deciding.')}</p></div></div> : null}
    <div className="grid gap-4 p-5 sm:grid-cols-2 sm:p-6 xl:grid-cols-4"><Metric icon={BookOpen} label="Course" value={application.Course} /><Metric icon={Building2} label="Institution" value={application.InstitutionName} /><Metric icon={Award} label="Previous marks" value={percent(application.PreviousYearMarks)} /><Metric icon={IndianRupee} label="Family income" value={money(application.AnnualFamilyIncome)} /><Metric icon={UserRound} label="Category / Gender" value={join(application.Category, application.Gender)} /><Metric icon={MapPin} label="Location" value={join(application.City, application.State)} /><Metric icon={CalendarDays} label="Enrollment" value={join(application.CurrentSemesterOrYear, application.EnrollmentYear)} /><Metric icon={UserRound} label="Family size" value={application.FamilySize} /></div>
    {(application.StatementOfPurpose || application.ExtracurricularActivities) ? <div className="grid gap-4 border-t border-border-soft p-5 sm:grid-cols-2 sm:p-6"><Narrative title="Statement of purpose" value={application.StatementOfPurpose} /><Narrative title="Extracurricular record" value={application.ExtracurricularActivities} /></div> : null}
  </section>;
}

function Metric({ icon: Icon, label, value }: { icon: React.ComponentType<{ className?: string }>; label: string; value: unknown }) { return <div className="rounded-lg border border-brand/8 bg-brand/[0.03] p-3"><p className="flex items-center gap-1.5 text-[9px] uppercase tracking-wider text-text-dim"><Icon className="h-3 w-3 text-brand" />{label}</p><p className="mt-1.5 break-words text-xs font-semibold text-text">{show(value)}</p></div>; }
function Narrative({ title, value }: { title: string; value: unknown }) { return <div><p className="text-[9px] uppercase tracking-wider text-text-dim">{title}</p><p className="mt-2 whitespace-pre-wrap text-xs leading-relaxed text-text-muted">{show(value)}</p></div>; }
function show(value: unknown, fallback = 'Not provided') { return value == null || value === '' ? fallback : String(value); }
function join(...values: unknown[]) { return values.filter((value) => value != null && value !== '').join(' · ') || undefined; }
function money(value: unknown) { const amount = Number(value); return Number.isFinite(amount) && amount >= 0 ? `₹${amount.toLocaleString('en-IN')}` : undefined; }
function percent(value: unknown) { const number = Number(value); return Number.isFinite(number) && number > 0 ? `${number}%` : undefined; }
function formatDate(value: unknown) { if (!value) return 'date unavailable'; const date = new Date(String(value)); return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleDateString('en-IN', { dateStyle: 'medium' }); }
