import { AlertTriangle, CheckCircle2, ExternalLink, FileText, History, Scale, ShieldCheck } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { API_BASE_URL } from '@/lib/api';
import type { EligibilityRuleView, ScreeningBGCheck, ScreeningDocument } from '@/types/screening';

export function ScreeningEvidenceReview({ application, documents, checks, rules, history }: {
  application: Record<string, unknown>; documents: ScreeningDocument[]; checks: ScreeningBGCheck[];
  rules: EligibilityRuleView[]; history: Record<string, unknown>[];
}) {
  const snapshot = application.EligibilitySnapshot as { isEligible?: boolean; results?: Array<Record<string, unknown>> } | null;
  return <div className="space-y-5"><section className="glass-card p-5 sm:p-6"><Title icon={Scale} eyebrow="Policy matrix" title="Eligibility evidence" help="Configured scholarship rules compared with the frozen application evidence." />
    {snapshot ? <div className={`mt-4 flex items-center gap-2 rounded-lg p-3 text-xs font-semibold ${snapshot.isEligible ? 'bg-success/10 text-success' : 'bg-danger/10 text-danger'}`}>{snapshot.isEligible ? <CheckCircle2 size={15} /> : <AlertTriangle size={15} />}Automated evaluation: {snapshot.isEligible ? 'Eligible' : 'Criteria exception detected'}</div> : <div className="mt-4 rounded-lg bg-gold/10 p-3 text-xs text-gold">No frozen automated evaluation is available for this legacy application. Complete a manual policy review.</div>}
    <div className="mt-4 grid gap-2 sm:grid-cols-2">{rules.map((rule) => { const result = snapshot?.results?.find((item) => Number(item.ruleId) === rule.RuleID); const passed = result?.passed; return <div key={rule.RuleID} className="rounded-lg border border-brand/10 p-3"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-semibold text-text">{rule.RuleType}</p><p className="mt-1 text-[10px] text-text-dim">{criteria(rule)}</p></div>{passed === undefined ? <span className="rounded bg-brand/5 px-2 py-1 text-[8px] font-semibold text-text-dim">Manual check</span> : <span className={`rounded px-2 py-1 text-[8px] font-semibold ${passed ? 'bg-success/10 text-success' : 'bg-danger/10 text-danger'}`}>{passed ? 'Met' : 'Not met'}</span>}</div><p className="mt-2 text-[9px] text-text-dim">{rule.IsRequired ? 'Required policy rule' : 'Advisory rule'}</p></div>; })}{!rules.length ? <p className="col-span-full py-6 text-center text-xs text-text-dim">No scholarship rules are configured.</p> : null}</div>
  </section>
  <div className="grid gap-5 lg:grid-cols-2"><section className="glass-card p-5"><Title icon={FileText} eyebrow="Document control" title="Verified documents" help="Open the reviewed source file before relying on it." /><div className="mt-4 space-y-2">{documents.map((doc) => <a key={doc.ChecklistID} href={fileUrl(doc.FileURL)} target="_blank" rel="noreferrer" className="group flex items-center gap-3 rounded-lg border border-brand/8 p-3 hover:border-brand/30 hover:bg-brand/[0.03]"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-md bg-brand/5 text-brand"><FileText size={14} /></span><span className="min-w-0 flex-1"><b className="block truncate text-xs text-text">{doc.DocumentType}</b><span className={`text-[9px] font-semibold ${doc.Status === 'Verified' ? 'text-success' : 'text-gold'}`}>{doc.Status}</span></span><ExternalLink size={12} className="text-text-dim group-hover:text-brand" /></a>)}{!documents.length ? <p className="py-6 text-center text-xs text-text-dim">No linked documents.</p> : null}</div></section>
    <section className="glass-card p-5"><Title icon={ShieldCheck} eyebrow="Independent verification" title="Background findings" help="Identity, address and income checks recorded by the field officer." /><div className="mt-4 space-y-2">{checks.map((check) => <div key={check.CheckType} className="rounded-lg border border-brand/8 p-3"><div className="flex items-center justify-between gap-2"><b className="text-xs text-text">{label(check.CheckType)}</b><span className={`rounded px-2 py-1 text-[8px] font-semibold ${check.Result === 'Pass' ? 'bg-success/10 text-success' : 'bg-danger/10 text-danger'}`}>{check.Result}</span></div><p className="mt-2 text-[10px] leading-relaxed text-text-muted">{check.Notes || 'No discrepancy was recorded.'}</p><p className="mt-2 text-[8px] text-text-dim">{check.CompletedAt ? dateTime(check.CompletedAt) : 'Completion time unavailable'}</p></div>)}{!checks.length ? <p className="py-6 text-center text-xs text-text-dim">No background findings.</p> : null}</div></section></div>
  <section className="glass-card p-5"><Title icon={History} eyebrow="Process integrity" title="Workflow trail" help="Stage transitions relevant to this application." /><div className="mt-4 divide-y divide-border-soft">{history.map((item, index) => <div key={`${String(item.CreatedAt)}-${index}`} className="flex gap-3 py-3"><span className="mt-1 h-2 w-2 shrink-0 rounded-full bg-brand" /><div><p className="text-xs font-semibold text-text">{show(item.FromStatus)} → {show(item.ToStatus)}</p><p className="mt-0.5 text-[9px] text-text-dim">{show(item.ActorRole)} · {dateTime(String(item.CreatedAt))}</p>{item.Reason ? <p className="mt-1 text-[10px] text-text-muted">{String(item.Reason)}</p> : null}</div></div>)}{!history.length ? <p className="py-6 text-center text-xs text-text-dim">No workflow events recorded.</p> : null}</div></section></div>;
}

function Title({ icon: Icon, eyebrow, title, help }: { icon: LucideIcon; eyebrow: string; title: string; help: string }) { return <div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-brand/10 text-brand"><Icon size={16} /></span><div><p className="text-[9px] uppercase tracking-[0.2em] text-gold">{eyebrow}</p><h2 className="text-sm font-semibold text-text">{title}</h2><p className="mt-0.5 text-[9px] text-text-dim">{help}</p></div></div>; }
function criteria(rule: EligibilityRuleView) { const values = rule.ValueList ? safeList(rule.ValueList).join(', ') : [rule.ValueMin, rule.ValueMax].filter(Boolean).join(' to '); return `${operator(rule.Operator)} ${values || 'configured value'}`; }
function operator(value: string) { return ({ LTE: 'At most', LT: 'Below', GTE: 'At least', GT: 'Above', EQ: 'Equal to', NEQ: 'Not equal to', IN: 'One of', NOT_IN: 'Not one of', BETWEEN: 'Between' } as Record<string, string>)[value] ?? value; }
function safeList(value: string) { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed.map(String) : [value]; } catch { return value.split(',').map((item) => item.trim()); } }
function fileUrl(path: string) { try { return new URL(path, API_BASE_URL).toString(); } catch { return '#'; } }
function label(value: string) { return value === 'IncomeVerification' ? 'Income verification' : value; }
function show(value: unknown) { return value == null || value === '' ? 'Start' : String(value); }
function dateTime(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }); }
